name: do-n8n
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: thewbear/do-n8n
    name: n8n
    run_command: "npm run start"
    envs:
      - key: N8N_PORT
        scope: RUN_TIME
        value: 80
      - key: N8N_HOST
        scope: RUN_TIME
        value: ${_self.PUBLIC_URL}
